# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c9d9369211afba18306115594c9847398a9f6fde506daa3fd46885741b1af23d3a442933f78d93d729ff77caa1719d5fa4f6fc3ee39012033621c58f5cf193

test:
  secret_key_base: 80d9cfdde206f937bd4637ea409eff99e14aa24aef0b3075da71e38a5e47b637f43fef67ad09b1d7fd2bd72df24ad786966210b4410cf6715ff1a566864ea6d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
