# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33149f0fdd7d925c50d1102579a4de2b2c68d6fc68001f95bc9b3b603f64b3b3e87d92dff6835c4fd1f0fe2eab36cd0b0fb6eeec7ddb2d29fcf2bdc19659becc

test:
  secret_key_base: cfc51def706503ce5087e7d8237b6c1ad0b6497b6cfecf5bd5839c316cfdeffef1245c05914b9888e495ac8ee7f9a220d259f8114c67e7508744c9f3e6e89877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
